import mongoose from "mongoose";
import dotenv from "dotenv";
import productModel from "./models/productModel.js";

dotenv.config();

// Using Unsplash URLs instead of local images (Node.js can't use React imports)
// These match your exact assets.js product structure with subCategory, sizes, bestseller

const products = [
  // ── WOMEN ──────────────────────────────────────────────────────
  {
    name: "Women Cotton Casual Top",
    description: "Soft breathable cotton top for everyday comfort.",
    price: 299,
    image: ["https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=400"],
    category: "Women",
    subCategory: "Topwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: true,
    date: Date.now(),
  },
  {
    name: "Women Floral Summer Dress",
    description: "Lightweight floral dress perfect for summer outings.",
    price: 189,
    image: ["https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=400"],
    category: "Women",
    subCategory: "Dress",
    sizes: ["S", "M", "L"],
    bestseller: true,
    date: Date.now(),
  },
  {
    name: "Women Office Blazer",
    description: "Elegant formal blazer designed for professional wear.",
    price: 320,
    image: ["https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400"],
    category: "Women",
    subCategory: "Topwear",
    sizes: ["S", "M", "L"],
    bestseller: false,
    date: Date.now(),
  },
  {
    name: "Women Slim Fit Jeans",
    description: "Stretchable slim-fit jeans with modern finish.",
    price: 220,
    image: ["https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=400"],
    category: "Women",
    subCategory: "Bottomwear",
    sizes: ["S", "M", "L"],
    bestseller: false,
    date: Date.now(),
  },
  {
    name: "Women Party Gown",
    description: "Premium party gown with elegant stitching.",
    price: 249,
    image: ["https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=400"],
    category: "Women",
    subCategory: "Dress",
    sizes: ["S", "M"],
    bestseller: true,
    date: Date.now(),
  },
  {
    name: "Women Winter Hoodie",
    description: "Warm fleece hoodie ideal for winter season.",
    price: 399,
    image: ["https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=400"],
    category: "Women",
    subCategory: "Winterwear",
    sizes: ["M", "L"],
    bestseller: true,
    date: Date.now(),
  },
  {
    name: "Women Denim Jacket",
    description: "Classic denim jacket for trendy look.",
    price: 374,
    image: ["https://images.unsplash.com/photo-1551537482-f2075a1d41f2?w=400"],
    category: "Women",
    subCategory: "Winterwear",
    sizes: ["S", "M", "L"],
    bestseller: true,
    date: Date.now(),
  },
  {
    name: "Women Maxi Dress",
    description: "Elegant maxi dress for special occasions.",
    price: 499,
    image: ["https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=400"],
    category: "Women",
    subCategory: "Dress",
    sizes: ["S", "M", "L", "XL"],
    bestseller: true,
    date: Date.now(),
  },
  {
    name: "Women Crop Top",
    description: "Trendy crop top made with soft fabric.",
    price: 600,
    image: ["https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=400"],
    category: "Women",
    subCategory: "Topwear",
    sizes: ["S", "M"],
    bestseller: false,
    date: Date.now(),
  },
  {
    name: "Women Long Coat",
    description: "Premium long coat for winter elegance.",
    price: 349,
    image: ["https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=400"],
    category: "Women",
    subCategory: "Winterwear",
    sizes: ["M", "L", "XL"],
    bestseller: true,
    date: Date.now(),
  },
  {
    name: "Women Printed Kurti",
    description: "Traditional printed kurti with modern touch.",
    price: 999,
    image: ["https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=400"],
    category: "Women",
    subCategory: "Dress",
    sizes: ["S", "M", "L"],
    bestseller: true,
    date: Date.now(),
  },
  {
    name: "Women Wool Sweater",
    description: "Soft wool sweater for cold weather.",
    price: 699,
    image: ["https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400"],
    category: "Women",
    subCategory: "Winterwear",
    sizes: ["S", "M"],
    bestseller: true,
    date: Date.now(),
  },
  {
    name: "Women Jumpsuit",
    description: "Trendy jumpsuit for modern fashion style.",
    price: 839,
    image: ["https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=400"],
    category: "Women",
    subCategory: "Dress",
    sizes: ["S", "M"],
    bestseller: false,
    date: Date.now(),
  },
  {
    name: "Women Skirt",
    description: "Comfortable midi skirt with stylish look.",
    price: 419,
    image: ["https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=400"],
    category: "Women",
    subCategory: "Bottomwear",
    sizes: ["S", "M"],
    bestseller: false,
    date: Date.now(),
  },
  {
    name: "Women Evening Dress",
    description: "Elegant evening dress for special events.",
    price: 741,
    image: ["https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400"],
    category: "Women",
    subCategory: "Dress",
    sizes: ["S", "M", "L"],
    bestseller: true,
    date: Date.now(),
  },
  {
    name: "Women Casual Kurti",
    description: "Printed kurti with breathable fabric.",
    price: 321,
    image: ["https://images.unsplash.com/photo-1585914924626-15adac1e6402?w=400"],
    category: "Women",
    subCategory: "Dress",
    sizes: ["S", "M"],
    bestseller: false,
    date: Date.now(),
  },

  // ── MEN ────────────────────────────────────────────────────────
  {
    name: "Men Cotton T-Shirt",
    description: "Comfortable cotton t-shirt with modern fit.",
    price: 529,
    image: ["https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=400"],
    category: "Men",
    subCategory: "Topwear",
    sizes: ["S", "M", "L"],
    bestseller: false,
    date: Date.now(),
  },
  {
    name: "Men Slim Fit Jeans",
    description: "Stretchable slim fit denim jeans.",
    price: 411,
    image: ["https://images.unsplash.com/photo-1542272604-787c3835535d?w=400"],
    category: "Men",
    subCategory: "Bottomwear",
    sizes: ["M", "L"],
    bestseller: true,
    date: Date.now(),
  },
  {
    name: "Men Formal Shirt",
    description: "Premium cotton formal shirt for office wear.",
    price: 300,
    image: ["https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=400"],
    category: "Men",
    subCategory: "Topwear",
    sizes: ["S", "M", "L"],
    bestseller: false,
    date: Date.now(),
  },
  {
    name: "Men Round Neck Pure Cotton T-shirt",
    description: "A lightweight, close-fitting pullover with a round neckline and short sleeves.",
    price: 276,
    image: ["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400"],
    category: "Men",
    subCategory: "Topwear",
    sizes: ["S", "M", "L", "XL"],
    bestseller: true,
    date: Date.now(),
  },
  {
    name: "Men Winter Jacket",
    description: "Heavy padded winter jacket with inner lining.",
    price: 291,
    image: ["https://images.unsplash.com/photo-1544923246-77307dd654cb?w=400"],
    category: "Men",
    subCategory: "Winterwear",
    sizes: ["M", "L"],
    bestseller: true,
    date: Date.now(),
  },
  {
    name: "Men Hoodie Sweatshirt",
    description: "Comfortable hoodie with adjustable drawstring.",
    price: 159,
    image: ["https://images.unsplash.com/photo-1509942774463-acf339cf87d5?w=400"],
    category: "Men",
    subCategory: "Winterwear",
    sizes: ["M", "L", "XL"],
    bestseller: false,
    date: Date.now(),
  },
  {
    name: "Men Polo T-Shirt",
    description: "Stylish polo t-shirt with premium finish.",
    price: 929,
    image: ["https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=400"],
    category: "Men",
    subCategory: "Topwear",
    sizes: ["S", "M", "L"],
    bestseller: true,
    date: Date.now(),
  },
  {
    name: "Men Tapered Trousers",
    description: "Slim fit flat-front trousers with modern look.",
    price: 652,
    image: ["https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=400"],
    category: "Men",
    subCategory: "Bottomwear",
    sizes: ["M", "L"],
    bestseller: false,
    date: Date.now(),
  },
  {
    name: "Men Denim Shirt",
    description: "Classic denim shirt for casual wear.",
    price: 300,
    image: ["https://images.unsplash.com/photo-1594938374182-a57d64e8eda4?w=400"],
    category: "Men",
    subCategory: "Topwear",
    sizes: ["S", "M", "L"],
    bestseller: false,
    date: Date.now(),
  },
  {
    name: "Men Sports Track Pants",
    description: "Breathable track pants for workout sessions.",
    price: 550,
    image: ["https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=400"],
    category: "Men",
    subCategory: "Bottomwear",
    sizes: ["M", "L"],
    bestseller: true,
    date: Date.now(),
  },
  {
    name: "Men Cargo Pants",
    description: "Multi-pocket cargo pants for rugged style.",
    price: 519,
    image: ["https://images.unsplash.com/photo-1565084888279-aca607ecce0c?w=400"],
    category: "Men",
    subCategory: "Bottomwear",
    sizes: ["M", "L"],
    bestseller: false,
    date: Date.now(),
  },
  {
    name: "Men Sports Jacket",
    description: "Lightweight jacket for sporty appearance.",
    price: 229,
    image: ["https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400"],
    category: "Men",
    subCategory: "Winterwear",
    sizes: ["M", "L"],
    bestseller: true,
    date: Date.now(),
  },
  {
    name: "Men Casual Shorts",
    description: "Comfortable cotton shorts for daily wear.",
    price: 897,
    image: ["https://images.unsplash.com/photo-1562183241-b937e9102303?w=400"],
    category: "Men",
    subCategory: "Bottomwear",
    sizes: ["M", "L"],
    bestseller: false,
    date: Date.now(),
  },
  {
    name: "Men Printed T-Shirt",
    description: "Stylish printed t-shirt with bold design.",
    price: 799,
    image: ["https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?w=400"],
    category: "Men",
    subCategory: "Topwear",
    sizes: ["S", "M", "L"],
    bestseller: true,
    date: Date.now(),
  },
  {
    name: "Men Track Jacket",
    description: "Comfortable track jacket for workouts.",
    price: 1999,
    image: ["https://images.unsplash.com/photo-1516826957135-700dedea698c?w=400"],
    category: "Men",
    subCategory: "Winterwear",
    sizes: ["M", "L"],
    bestseller: true,
    date: Date.now(),
  },
  {
    name: "Men Formal Trousers",
    description: "Classic formal trousers for office wear.",
    price: 619,
    image: ["https://images.unsplash.com/photo-1490657419715-de34e6a1f95e?w=400"],
    category: "Men",
    subCategory: "Bottomwear",
    sizes: ["M", "L", "XL"],
    bestseller: false,
    date: Date.now(),
  },
  {
    name: "Men Casual Hoodie",
    description: "Warm and stylish casual hoodie.",
    price: 599,
    image: ["https://images.unsplash.com/photo-1520975954732-35dd22299614?w=400"],
    category: "Men",
    subCategory: "Winterwear",
    sizes: ["M", "L"],
    bestseller: false,
    date: Date.now(),
  },
  {
    name: "Men Classic Blazer",
    description: "Premium tailored blazer for formal occasions.",
    price: 852,
    image: ["https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400"],
    category: "Men",
    subCategory: "Topwear",
    sizes: ["M", "L", "XL"],
    bestseller: true,
    date: Date.now(),
  },

  // ── KIDS ───────────────────────────────────────────────────────
  {
    name: "Kids Cartoon T-Shirt",
    description: "Soft cotton t-shirt with fun cartoon prints.",
    price: 499,
    image: ["https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=400"],
    category: "Kids",
    subCategory: "Topwear",
    sizes: ["S", "M", "L"],
    bestseller: true,
    date: Date.now(),
  },
  {
    name: "Kids Denim Shorts",
    description: "Durable denim shorts for active kids.",
    price: 599,
    image: ["https://images.unsplash.com/photo-1471286174890-9c112ffca5b4?w=400"],
    category: "Kids",
    subCategory: "Bottomwear",
    sizes: ["S", "M"],
    bestseller: false,
    date: Date.now(),
  },
  {
    name: "Kids Winter Jacket",
    description: "Warm padded jacket to keep kids cozy in winter.",
    price: 799,
    image: ["https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=400"],
    category: "Kids",
    subCategory: "Winterwear",
    sizes: ["S", "M"],
    bestseller: true,
    date: Date.now(),
  },
];

mongoose
  .connect(process.env.MONGO_URI)
  .then(async () => {
    console.log("MongoDB Connected ✅");

    // Clear old products first to avoid duplicates
    await productModel.deleteMany();
    console.log("Old products cleared 🗑️");

    await productModel.insertMany(products);
    console.log(`${products.length} products seeded successfully ✅`);

    process.exit();
  })
  .catch((err) => {
    console.log("Error:", err);
    process.exit(1);
  });